### ISSUE TITLE
OTP is not functioning in Proguard enabled signed apk

### ISSUE THREAD

**Issue by androidser** [MSG91/sendotp-android#36] opened 2020-09-07 07:13 UTC
I've integrated MSg91 in my Android app. Msg91 OTP functionalities are working properly in debug apk. But in signed apk, OTP functionalities are not working. Neither receive otp nor it automatically verifies. onSendOtpResponse function is called anymore.

**Comment by AdityaIsHere** [comment] 2020-09-07 09:09
checking...

**Comment by AdityaIsHere** [comment] 2020-09-07 09:17
Hello @androidser 
can you please let us know if you are using the signed bundle or the signed APK?
if Signed APK, why are you using it? can you mention the purpose?

**Comment by androidser** [comment] 2020-09-07 09:48
It is not working in signed bundle also. And for testing purposes, I'm using signed APK

**Comment by AdityaIsHere** [comment] 2020-09-07 09:49
ok, can you mention for which Android versions it is not working?

**Comment by androidser** [comment] 2020-09-07 09:51
I've tested it on android 6,7 and 8. targetSdkVersion in my project is 30

**Comment by androidser** [comment] 2020-09-07 10:17
The error shows that package name and application Id are different while I'm using signed apk.
But both are same. When I pass applicationid to the SendOTP.initializeApp(context,applicationid) function, it shows invalid applicationid. How can I solve this? please suggest me a solution for this. All these things are happening only in signed apk

**Comment by AdityaIsHere** [comment] 2020-09-07 10:32
ok, trying to reproduce this

**Comment by AdityaIsHere** [comment] 2020-09-07 13:45
[Here](https://github.com/MSG91/sendotp-android/issues/29)

Looks Like this issue is copy of one of closed issue
please check once

**Comment by androidser** [comment] 2020-09-07 16:18
I've checked it. My package name and applicationid are same. 
This is how I done SendOTP.initializeApp(getApplication(), "com.android.example");
However, this is working in debug apk only. And we can't upload debug apk to play console. That's the problem.
It is not resolved.

**Comment by walkoverricha** [comment] 2020-09-08 10:14
Hello @androidser 
We have tested it with signed apk and bundle both on 6, 7, and 8th version and it seems working fine as we are not able to reproduce this at our end. passed the same application id endOTP.initializeApp(getApplication(), "here");
May you please share your app-level build.gradle file and manifest file? so that we can check.

**Comment by androidser** [comment] 2020-09-11 10:17
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

The issue is because of enabling proguard. Please provide a solution to this

**Comment by walkoverricha** [comment] 2020-09-12 12:27
Hello @androidser 
We were able to reproduce it, now we understand, thank you for reporting this issue.
We are looking into it, as soon as it will be fixed, we will ping you here and will inform you on the best possible communication channel.
It should take minimum one day
Thanks!

**Comment by androidser** [comment] 2020-09-12 13:35
Okay, I believe that this issue will resolve in maximum one day. And I've to deploy the app with msg91 library in google play console so I can't disable Proguard for any reason.

**Comment by androidser** [comment] 2020-09-12 13:36
Okay, I believe that this issue will be resolved in maximum one day. And I've to deploy the app with msg91 library in google play console so I can't disable Proguard for any reason.

**Comment by AdityaIsHere** [comment] 2020-09-13 14:29
Hi @androidser, the issue is not resolved yet, we are constantly working on it to fix it
Will post here as it is fixed 
Please bear with us. 
Thanks

**Comment by AdityaIsHere** [comment] 2020-09-14 07:39
@androidser the issue is fixed, we are staging the changes, will ping as done!

**Comment by androidser** [comment] 2020-09-14 12:03
Okay, thank you. I hope the changes are available as an update to the library as soon as possible.

**Comment by walkoverricha** [comment] 2020-09-15 06:28
The issue has been fixed on new update the version 1.3.8, Please check the readme file for update
@androidser please use updated version 1.3.8

**Comment by androidser** [comment] 2020-09-15 06:46
Okay let me check

**Comment by androidser** [comment] 2020-09-15 06:56
Failed to resolve: com.msg91.sendotpandroid.library:library:1.3.8

**Comment by androidser** [comment] 2020-09-15 07:09
![2020-09-15_12h29_05](https://user-images.githubusercontent.com/70881190/93177380-55f84600-f750-11ea-84ba-a0646e875d91.png)

**Comment by AdityaIsHere** [comment] 2020-09-15 07:43
@androidser 
Changes are merged now, please check the Readme file once again, there are changes in the library in terms of implementation, and please let us know if the issue is fixed or not at your end! 
Thanks

**Comment by androidser** [comment] 2020-09-15 07:48
Failed to resolve: com.msg91.sendotpandroid.library:library:1.3.8
This is what I'm getting..

**Comment by AdityaIsHere** [comment] 2020-09-15 07:54
please check the ReadMe file once

**Comment by androidser** [comment] 2020-09-15 07:56
Readme file updated few minutes ago for me. Now I can see the changes. I'm checking..

**Comment by androidser** [comment] 2020-09-15 08:08
responseCode is UNKNOWN_BEHAVIOUR. Why is this happening?

**Comment by AdityaIsHere** [comment] 2020-09-15 08:35
@androidser 
please share screenshot of this error

**Comment by androidser** [comment] 2020-09-15 08:52
![2020-09-15_14h19_53](https://user-images.githubusercontent.com/70881190/93188585-c7d78c00-f75e-11ea-8d1e-16a89fc43f88.png)

**Comment by AdityaIsHere** [comment] 2020-09-15 08:54
@androidser 
have you checked the ApplicationClass.java's changes, you have to make?

**Comment by androidser** [comment] 2020-09-15 08:56
![2020-09-15_14h25_38](https://user-images.githubusercontent.com/70881190/93189142-7380dc00-f75f-11ea-92f8-9fb9a0ca337e.png)

**Comment by AdityaIsHere** [comment] 2020-09-15 08:58
@androidser 
you just need to pass the key in second param, not with key **SEND_OTP_KEY:**

SendOTP.initializeApp(this, "Key goes here");

Like this

**Comment by androidser** [comment] 2020-09-15 08:58
Now it's changed to SendOTP.initializeApp(this,authkey)

**Comment by AdityaIsHere** [comment] 2020-09-15 08:59
@androidser 
Let me if it works for you...

**Closed as completed** 2020-09-15 09:55 UTC
